//! Host-synthesized `AGENTS.md` for a mount root.
//!
//! Every mount projects a synthetic, read-only `AGENTS.md` at its root that
//! teaches an agent how to navigate the provider. The bytes are assembled
//! host-side from metadata the host already holds (`provider-info` plus the
//! static [`ProviderManifest`]) — no provider authority and no provider code
//! is involved (the byte-boundary invariant: this is documentation derived
//! from paths/bytes the host owns, not new reasoning pushed into the host).
//!
//! The bytes are computed once at [`Runtime`](crate::Runtime) construction and
//! held verbatim, so the size reported by `lookup`/`readdir` and the bytes
//! returned by `read` are the same buffer and can never disagree
//! (`stat`/`cat`/`wc -c` honesty).
//!
//! Injection lives in the shared host layer (`namespace`), so both the FUSE and
//! NFS frontends inherit the leaf for free; it is never frontend-specific.

use std::fmt::Write as _;

use omnifs_provider::{CapabilityEntry, ProviderManifest};
use omnifs_wit::provider::types as wit_types;

/// The synthetic leaf's name at the mount root.
pub const AGENTS_MD_NAME: &str = "AGENTS.md";
/// The content type the host echoes for the synthetic leaf.
pub const AGENTS_MD_CONTENT_TYPE: &str = "text/markdown";

/// A mount root's pre-rendered `AGENTS.md`.
///
/// Built once and held verbatim so the advertised size and the read bytes are
/// the same buffer.
#[derive(Debug, Clone)]
pub struct AgentsDoc {
    bytes: Vec<u8>,
}

impl AgentsDoc {
    /// Render the doc from the provider's live `provider-info` and its static
    /// manifest. `mount_name` is the path segment the provider is mounted under
    /// (used only to show the agent where the tree lives).
    #[must_use]
    pub fn render(
        mount_name: &str,
        info: &wit_types::ProviderInfo,
        manifest: Option<&ProviderManifest>,
    ) -> Self {
        Self {
            bytes: render_markdown(mount_name, info, manifest).into_bytes(),
        }
    }

    /// The rendered markdown bytes. The advertised size is exactly this length.
    #[must_use]
    pub fn bytes(&self) -> &[u8] {
        &self.bytes
    }

    /// Exact byte length of the rendered doc — the size `lookup`/`readdir` must
    /// advertise so `stat`/`wc -c`/`head -c` agree with `read`.
    #[must_use]
    pub fn len(&self) -> u64 {
        self.bytes.len() as u64
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.bytes.is_empty()
    }
}

/// Assemble the markdown. Deterministic: route order follows
/// `provider-info().routes` (registration order); no map iteration drives the
/// output. Only honest, provider-supplied metadata is emitted — no invented
/// routes, no over-claimed reach.
fn render_markdown(
    mount_name: &str,
    info: &wit_types::ProviderInfo,
    manifest: Option<&ProviderManifest>,
) -> String {
    let mut out = String::new();

    let title = manifest
        .map(|m| m.display_name.as_str())
        .filter(|name| !name.trim().is_empty())
        .unwrap_or(info.name.as_str());
    let _ = writeln!(out, "# {title}");
    out.push('\n');

    let _ = writeln!(
        out,
        "`{}` v{} — projected at `/{}`.",
        info.name, info.version, mount_name
    );
    if !info.description.trim().is_empty() {
        out.push('\n');
        let _ = writeln!(out, "{}", info.description.trim());
    }
    out.push('\n');

    let _ = writeln!(
        out,
        "This file is generated by omnifs from the provider's route map and \
         metadata. It is read-only and explains how to navigate this mount."
    );
    out.push('\n');

    render_routes(&mut out, &info.routes);

    if let Some(manifest) = manifest {
        render_capabilities(&mut out, &manifest.capabilities);
        render_auth(&mut out, manifest);
    }

    out
}

/// Render the route table as a nested list, mirroring the tree-build the
/// `provider info` CLI and the `introspect_routes` bin use: every parent
/// precedes its children in the flattened list, so a single backward pass
/// reattaches them.
fn render_routes(out: &mut String, flat: &[wit_types::RouteDescriptor]) {
    let _ = writeln!(out, "## Navigating this provider");
    out.push('\n');

    if flat.is_empty() {
        let _ = writeln!(out, "_This provider registers no routes._");
        out.push('\n');
        return;
    }

    for node in &rebuild_tree(flat) {
        render_route_node(out, node, 0);
    }
    out.push('\n');
}

fn render_route_node(out: &mut String, node: &RouteNode, depth: usize) {
    let indent = "  ".repeat(depth);
    let _ = writeln!(
        out,
        "{indent}- `{}` ({})",
        node.template,
        kind_label(node.kind)
    );
    if let Some(description) = &node.description {
        let description = description.trim();
        if !description.is_empty() {
            let _ = writeln!(out, "{indent}  - {description}");
        }
    }
    if !node.representations.is_empty() {
        let _ = writeln!(
            out,
            "{indent}  - representations: {}",
            node.representations.join(", ")
        );
    }
    for child in &node.children {
        render_route_node(out, child, depth + 1);
    }
}

fn render_capabilities(out: &mut String, capabilities: &[CapabilityEntry]) {
    if capabilities.is_empty() {
        return;
    }
    let _ = writeln!(out, "## Capabilities");
    out.push('\n');
    let _ = writeln!(
        out,
        "External systems this provider may reach (host-enforced; the provider \
         cannot exceed these grants):"
    );
    out.push('\n');
    for entry in capabilities {
        let _ = writeln!(
            out,
            "- {} `{}` — {}",
            capability_kind_label(entry),
            capability_value(entry),
            entry.why().trim()
        );
    }
    out.push('\n');
}

fn render_auth(out: &mut String, manifest: &ProviderManifest) {
    let Some(auth) = &manifest.auth else {
        return;
    };
    if auth.schemes.is_empty() {
        return;
    }
    let _ = writeln!(out, "## Authentication");
    out.push('\n');
    let _ = writeln!(
        out,
        "This provider authenticates to its upstream. Credentials are held by \
         the host, never by the provider. Auth schemes:"
    );
    out.push('\n');
    // BTreeMap iteration is ordered, so the rendering is deterministic.
    for key in auth.schemes.keys() {
        let marker = if key == &auth.default {
            " (default)"
        } else {
            ""
        };
        let _ = writeln!(out, "- `{key}`{marker}");
    }
    out.push('\n');
}

fn kind_label(kind: wit_types::RouteKind) -> &'static str {
    match kind {
        wit_types::RouteKind::Dir => "dir",
        wit_types::RouteKind::File => "file",
        wit_types::RouteKind::TreeRef => "tree-ref",
        wit_types::RouteKind::Object => "object",
        wit_types::RouteKind::FileObject => "file-object",
    }
}

fn capability_kind_label(entry: &CapabilityEntry) -> &'static str {
    match entry {
        CapabilityEntry::Domain { .. } => "domain",
        CapabilityEntry::GitRepo { .. } => "git repo",
        CapabilityEntry::UnixSocket { .. } => "unix socket",
        CapabilityEntry::PreopenedPath { .. } => "preopened path",
        CapabilityEntry::MemoryMb { .. } => "memory (MB)",
        CapabilityEntry::FetchBlobBytes { .. } => "fetch blob bytes",
        CapabilityEntry::ReadBlobBytes { .. } => "read blob bytes",
    }
}

fn capability_value(entry: &CapabilityEntry) -> String {
    match entry {
        CapabilityEntry::Domain { value, .. }
        | CapabilityEntry::GitRepo { value, .. }
        | CapabilityEntry::UnixSocket { value, .. } => value.clone(),
        CapabilityEntry::PreopenedPath { value, .. } => format!("{value:?}"),
        CapabilityEntry::MemoryMb { value, .. } => value.to_string(),
        CapabilityEntry::FetchBlobBytes { value, .. }
        | CapabilityEntry::ReadBlobBytes { value, .. } => value.to_string(),
    }
}

/// A node in the rebuilt route tree.
struct RouteNode {
    template: String,
    kind: wit_types::RouteKind,
    description: Option<String>,
    representations: Vec<String>,
    children: Vec<RouteNode>,
}

/// Rebuild the nested route tree from the flattened WIT list. Each entry's
/// `parent` is the index of its parent in the same list; every parent precedes
/// its children, so a single backward pass reattaches children. Mirrors the
/// `provider info` CLI and the `introspect_routes` bin.
fn rebuild_tree(flat: &[wit_types::RouteDescriptor]) -> Vec<RouteNode> {
    let mut nodes: Vec<(Option<u32>, RouteNode)> = flat
        .iter()
        .map(|r| {
            (
                r.parent,
                RouteNode {
                    template: r.template.clone(),
                    kind: r.kind,
                    description: r.description.clone(),
                    representations: r.representations.clone(),
                    children: Vec::new(),
                },
            )
        })
        .collect();

    let mut roots = Vec::new();
    while let Some((parent, node)) = nodes.pop() {
        match parent {
            Some(idx) => {
                let idx = idx as usize;
                if idx < nodes.len() {
                    nodes[idx].1.children.insert(0, node);
                } else {
                    roots.insert(0, node);
                }
            },
            None => roots.insert(0, node),
        }
    }
    roots
}
